### ISSUE TITLE
Review Model and Log Outputs

### ISSUE THREAD

**Issue by mmcleod89** [UCL/hivpy#115]
With a view to running interactive session with epidemiology team. Should be consulting with them on the outputs that would be useful to see for this purpose.

**Comment by mmcleod89** [comment]
- [x] Fix output module to use new dataframe accessors #129 
- [x] Consult with HIV team and determine outputs for pregnancy and ANC testing #130 
- [ ] Add some way for a user to specify which columns from the dataframe they'd like to track for plotting #33
